print('Hello Exception')
if(1==1):
    raise Exception